# Generated by Django 5.2.13 on 2026-07-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_report_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo (pago completo)'), ('PARTIAL', 'Pago parcial'), ('EXPIRED', 'Vencido')], default='ACTIVE', help_text='Activo si el monto cubre el precio del plan; Parcial si falta saldo (varios pagos parciales pueden sumar). Vencido: sin acceso.', max_length=16, verbose_name='estado'),
        ),
    ]
