# Generated by Django 5.2.13 on 2026-07-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_attendance_date_index'),
        ('clients', '0003_client_access_number_blank'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='uniq_attendance_per_client_day',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(help_text='Día civil local (America/Mexico_City). Puede haber varias asistencias el mismo día (una por ingreso).', verbose_name='día de asistencia'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['client', 'attendance_date'], name='attendances_client_date_idx'),
        ),
    ]
