# Generated by Django 5.2.13 on 2026-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_demo_client_and_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',), 'verbose_name': 'nadador', 'verbose_name_plural': 'nadadores'},
        ),
        migrations.AlterField(
            model_name='client',
            name='access_number',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador único para ingreso en recepción. Se asigna automáticamente al crear (AAAAMM + consecutivo).', max_length=32, unique=True, verbose_name='número de acceso'),
        ),
    ]
