# Generated by Django 5.2.13 on 2026-07-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_access_number_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Número celular para mostrar en la credencial.', max_length=20, verbose_name='celular de emergencia'),
        ),
    ]
