# Generated by Django 5.2.13 on 2026-07-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_set_plan_prices'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membershipplan',
            name='membershipplan_price_positive',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='class_quota',
            field=models.PositiveIntegerField(blank=True, help_text='Número de clases en el periodo de vigencia del pago. Vacío = ilimitado (becados).', null=True, verbose_name='clases incluidas'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='max_visits_per_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tope de visitas el mismo día. Vacío = sin tope diario.', null=True, verbose_name='máximo de ingresos por día'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='allowed_days',
            field=models.JSONField(default=list, help_text='Días de la semana en que el socio puede asistir (lunes a domingo).', verbose_name='días permitidos'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Costo total de la membresía (MXN). Use 0 para becados. La suma de pagos vigentes del cliente debe alcanzar este monto para permitir ingreso (salvo precio 0).', max_digits=12, verbose_name='precio del paquete'),
        ),
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='membershipplan_price_non_negative'),
        ),
    ]
